[theme]
base="dark"

primaryColor="#FF9900"
backgroundColor="#000000" 
textColor="#ffffff"

# Widgets 
showWidgetBorder = true 
borderColor = "#ffffff"

font="monospace"
baseFontSize = 10 
headingFontSizes = ["2.5rem","1.5rem","1rem"]

[server]
headless = true
runOnSave = true

[browser]
gatherUsageStats = false