
"""
import os 
from pathlib import Path 
PROJECT_ROOT = ""
SRC_PATH = ""
for parent in Path(__file__).parents:
        if (parent / "src").exists():
           PROJECT_ROOT = parent     
           SRC_PATH = parent / "src"
           break
    
os.chdir(SRC_PATH)
"""
import os 
import streamlit as st
import pandas as pd 
import numpy as np 
import altair as alt
from typing import Dict
from pathlib import Path
from app_util.parquet_loader import parquet_loader

st.set_page_config(
    page_title="## ALM Interest Rate Hedging Prototype & Dashboard",
    layout="wide", 
    initial_sidebar_state="expanded"
)

# CSS
st.markdown("""
<style>

/* ---- Base font size ---- */
html, body, [data-testid="stAppViewContainer"] {
    font-size: 10pt;
}

/* ---- Title (h1) ---- */
h1 {
    font-size: 12pt !important;
}

/* ---- Subheaders (h2, h3 etc.) ---- */
h2, h3 {
    font-size: 10pt !important;
}

/* ---- Spacing under headers ---- */
h1, h2, h3 {
    margin-bottom: 0.3rem; 
}

</style>
""", unsafe_allow_html=True)

st.header("Interest Rate Risk Hedging – ALM Prototype")

st.markdown("---")

st.markdown("""
This project consists of two closely related components:

- **`alm_ir_hedging_prototype`**: a Python library for modelling and managing interest rate risk in an Asset-Liability Management (ALM) context.  
- **`alm_ir_hedging_app`**: a Streamlit dashboard that visualizes model outputs and enables analysis of risk exposures and hedging strategies.

**`alm_ir_hedging_prototype`** implements a full end-to-end workflow for interest rate risk analysis and hedging:
- Calibration and bootstrapping of EUR swap curves (EURIBOR 6M)
- Risk factor analysis using PCA and Monte Carlo simulation of swap rate curves based on historical covariance (using Cholesky decomposition)
- Modelling of pension-style liability profiles and pricing of interest rate swaps (IRS) for construction of hedges and overlays
- Calculation of risk sensitivities (Spot/Forward PV01, key rate exposures, gamma) and Monte Carlo CVaR with full revaluation of liabilities and hedging instruments across scenarios  
- Development of hedging strategies, specifically:
  - Full immunization (benchmark hedge)
  - Variance-minimizing hedge using liquid market instruments, derived via General Least Squares (GLS)

**`alm_ir_hedging_app`** consumes precomputed results (generated by alm_ir_hedging_prototype and stored as parquet files) and presents streamlit dashboard with:
- Risk factor decomposition  
- Liability risk analysis  
- Hedge construction and performance comparison  

Each dashboard page includes an **info** panel (dropdown), with concise descriptions of the key derivations and modelling choices. 
Core curve construction and pricing are built on top of  **Rateslib**, while the surrounding risk modelling, simulation, and hedging framework is implemented from scratch.
This project is not intended as prodcution-ready application - aim is to demonstrate proficiency level within quantitative modelling, risk management and Python. 
Scope is narrowed in terms of instruments (choice is limited to fixed/float IRS) and risk factors (only outright IR risk is considered - tenor basis, gamma, vega and FX risks are ignored).  
These are left as natural next steps/extensions. The full solution was designed and implemented in approximately **3 weeks**.

Both components are available as separate GitHub repositories:
- Prototype: https://github.com/dubayevmagomed/alm-ir-hedging-prototype
- Application: https://github.com/dubayevmagomed/alm-ir-hedging-app
""")

st.markdown("---")

st.markdown("""
### Use the sidebar to navigate

- risk factors 
- liabilities  
- hedges  
""")
